version: '3'

services:
  gosvc:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - net

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crud
      - MYSQL_PASSWORD=root
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    networks:
      - net

networks:
  net:
    driver: bridge

